# This is a basic workflow to help you get started with Actions

name: Netlify Builds

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: log untrusted output
      run: |

        # disable command workflow processing
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"

        # log untrusted output
        echo "untrusted output"

        # enable workflow command processing
        echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"

    # Runs a set of commands using the runners shell
    - name: Build the site
      run: |
        yarn install --production
        yarn build
        
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.1.3
      with:
          publish-dir: './public'
          production-branch: master
          deploy-message: '${{ github.event.head_commit.message }}'
      env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
